### PR TITLE
Do an overhaul

### PR DESCRIPTION
**Pull request by terop**
Changes:
* Update deps.edn
* Fix the library to work with a newer version of webauthn4j-core
* Add comments to front-end to make it more easily usable with USB
  tokens
* Fix typos and a clj-kondo warning

### CODE REVIEW

**Comment by terop** [comment]
I also updated the sample application's pages to use the latest versions of all libraries. I can open a PR for that as well if that is requested.

**Comment by agrison** [comment]
Awesome upgrade ✨ 
Thank you @terop 🚀 

Do let me know if you have something else so that I can wait for it to merge.

I'll push on clojars next week, won't have the time this weekend.

**Comment by terop** [comment]
I have a few changes for the first commit  which I now pushed. I also pushed the front-end lib update to this review.

For now I don't have any other changes but I am still in the middle of integrating your library in to my application so I might have further changes in the future but I will open PR(s) for those if such changes actually come about.

**Comment by terop** [comment]
@agrison would you have time to merge this PR and create a new release in Clojars?

**Comment by agrison** [comment]
@terop You will find it on clojars as version `0.1.3` here: https://clojars.org/me.grison/cljwebauthn

**Comment by terop** [comment]
Many thanks @agrison!

**Pull request merged**
